{"level":"error","message":"Error: URL not found\n    at UrlService.getUrl (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\services\\url.service.js:41:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async redirect (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\url.controller.js:28:19)","timestamp":"2025-01-18T01:35:07.068Z"}
{"level":"error","message":"Error: Wrong recipient, payload audience != requiredAudience\n    at OAuth2Client.verifySignedJwtWithCertsAsync (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\google-auth-library\\build\\src\\auth\\oauth2client.js:750:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async OAuth2Client.verifyIdTokenAsync (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\google-auth-library\\build\\src\\auth\\oauth2client.js:508:23)\n    at async googleSignIn (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\auth.controller.js:11:22)","timestamp":"2025-01-18T01:38:22.599Z"}
{"level":"error","message":"Error: Wrong recipient, payload audience != requiredAudience\n    at OAuth2Client.verifySignedJwtWithCertsAsync (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\google-auth-library\\build\\src\\auth\\oauth2client.js:750:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async OAuth2Client.verifyIdTokenAsync (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\google-auth-library\\build\\src\\auth\\oauth2client.js:508:23)\n    at async googleSignIn (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\auth.controller.js:11:22)","timestamp":"2025-01-18T01:40:26.814Z"}
{"level":"error","message":"Error: Wrong recipient, payload audience != requiredAudience\n    at OAuth2Client.verifySignedJwtWithCertsAsync (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\google-auth-library\\build\\src\\auth\\oauth2client.js:750:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async OAuth2Client.verifyIdTokenAsync (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\google-auth-library\\build\\src\\auth\\oauth2client.js:508:23)\n    at async googleSignIn (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\auth.controller.js:12:22)","timestamp":"2025-01-18T01:41:26.868Z"}
{"level":"error","message":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at googleSignIn (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\auth.controller.js:28:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-01-18T01:44:26.405Z"}
{"level":"error","message":"Error: URL not found\n    at UrlService.getUrl (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\services\\url.service.js:41:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async redirect (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\url.controller.js:28:19)","timestamp":"2025-01-18T01:55:06.189Z"}
{"level":"error","message":"ValidationError: Url validation failed: topic: `nature` is not a valid enum value for path `topic`.\n    at Document.invalidate (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\mongoose\\lib\\document.js:3334:32)\n    at C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\mongoose\\lib\\document.js:3095:17\n    at C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\mongoose\\lib\\schemaType.js:1407:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-01-18T01:55:27.459Z"}
{"level":"error","message":"Error: URL not found\n    at UrlService.getUrl (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\services\\url.service.js:41:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async getUrlAnalytics (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\url.controller.js:44:19)","timestamp":"2025-01-18T02:27:27.104Z"}
{"level":"error","message":"Error: URL not found\n    at UrlService.getUrl (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\services\\url.service.js:41:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async getUrlAnalytics (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\url.controller.js:44:19)","timestamp":"2025-01-18T02:27:55.986Z"}
{"level":"error","message":"Error: URL not found\n    at UrlService.getUrl (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\services\\url.service.js:41:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async getUrlAnalytics (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\url.controller.js:44:19)","timestamp":"2025-01-18T02:28:38.762Z"}
{"level":"error","message":"Error: URL not found\n    at UrlService.getUrl (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\services\\url.service.js:41:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async getUrlAnalytics (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\url.controller.js:44:19)","timestamp":"2025-01-18T02:29:09.598Z"}
{"level":"error","message":"ReferenceError: token is not defined\n    at googleSignIn (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\auth.controller.js:11:19)\n    at Layer.handle [as handle_request] (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\express\\lib\\router\\index.js:47:12)","timestamp":"2025-01-18T04:14:21.121Z"}
{"level":"error","message":"MongoDB Connection Error: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"ac-cltrz42-shard-00-00.7cflh58.mongodb.net:27017":{"$clusterTime":null,"address":"ac-cltrz42-shard-00-00.7cflh58.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":76767294,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"ac-cltrz42-shard-00-01.7cflh58.mongodb.net:27017":{"$clusterTime":null,"address":"ac-cltrz42-shard-00-01.7cflh58.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":76767302,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"ac-cltrz42-shard-00-02.7cflh58.mongodb.net:27017":{"$clusterTime":null,"address":"ac-cltrz42-shard-00-02.7cflh58.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":76767600,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-7f4u08-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\mongoose\\lib\\connection.js:1110:11)\n    at NativeConnection.openUri (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\mongoose\\lib\\connection.js:1041:11)\n    at async connectDB (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\config\\db.js:6:5)","timestamp":"2025-01-19T01:21:08.063Z"}
{"level":"error","message":"ValidationError: Url validation failed: topic: `random` is not a valid enum value for path `topic`.\n    at Document.invalidate (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\mongoose\\lib\\document.js:3334:32)\n    at C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\mongoose\\lib\\document.js:3095:17\n    at C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\node_modules\\mongoose\\lib\\schemaType.js:1407:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-01-19T01:24:17.394Z"}
{"level":"error","message":"Error: URL not found\n    at UrlService.getUrl (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\services\\url.service.js:41:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async redirect (C:\\Users\\HP\\OneDrive\\Desktop\\Assign1\\Backend\\controllers\\url.controller.js:28:19)","timestamp":"2025-01-19T01:25:18.751Z"}
